import Head from "next/head"
import ImageGrid from "../components/ImageGrid"
import { collection, getDocs } from "firebase/firestore"
import { db } from "../public/firebase/firebase"

export default function Home({ imgList }) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ImageGrid imgList={imgList}></ImageGrid>
		</div>
	)
}

export const getServerSideProps = async (context) => {
	let list = []
	try {
		const querySnapshot = await getDocs(collection(db, "slike"))
		querySnapshot.forEach((doc) => {
			list.push({ id: doc.id, ...doc.data() })
		})

		return {
			props: { imgList: list },
		}
	} catch (err) {
		console.log(err)
		return { props: {} }
	}
}
